from datetime import datetime
from enum import Enum
from pydantic import BaseModel
from pydantic import Field


class ContentMode(str, Enum):
    horror = "horror"
    wealth = "wealth"
    softskills = "softskills"
    mystery = "mystery"
    # Kept for backward compat — worker maps sales→wealth, story→horror
    sales = "sales"
    story = "story"


class ContentOption(BaseModel):
    """A single title + content pair generated by the LLM for user to choose from."""
    title: str
    content: str


class GenerateOptionsRequest(BaseModel):
    mode: ContentMode
    language: str = Field(default="en")
    tone: str = Field(default="friendly")
    count: int = Field(default=3, ge=2, le=5)


class GenerateOptionsResponse(BaseModel):
    options: list[ContentOption]


class SelectOptionRequest(BaseModel):
    mode: ContentMode
    language: str = Field(default="en")
    tone: str = Field(default="friendly")
    selected_index: int = Field(default=0, ge=0)
    options: list[ContentOption]  # the full list so worker can pick the chosen one
    use_gemini_refine: bool = Field(default=False)


class AudioVideoOptions(BaseModel):
    create_audio: bool = Field(default=True)
    create_video: bool = Field(default=False)
    video_source_type: str = Field(default="self", description="self or internet")
    user_video_path: str | None = Field(default=None)
    voice_sample_filename: str | None = Field(default=None)
    edge_tts_voice: str | None = Field(default=None)
    kokoro_voice: str | None = Field(default="af_heart")
    video_keyword: str | None = Field(default=None)
    notify_telegram: bool = Field(default=False)
    telegram_chat_id: str | None = Field(default=None)


class JobRequest(BaseModel):
    mode: ContentMode
    title: str = Field(min_length=3, max_length=500)
    content: str = Field(min_length=50, max_length=200000)
    language: str = Field(default="en")
    tone: str = Field(default="friendly")
    use_gemini_refine: bool = Field(default=False)
    create_audio: bool = Field(default=True)
    create_video: bool = Field(default=False)
    video_source_type: str = Field(default="self", description="self, internet, or image")
    user_video_path: str | None = Field(default=None)
    user_image_path: str | None = Field(default=None)
    voice_sample_filename: str | None = Field(default=None)
    edge_tts_voice: str | None = Field(default=None)
    kokoro_voice: str | None = Field(default="af_heart")
    video_keyword: str | None = Field(default=None)
    feedback_note: str | None = Field(default=None, max_length=500)
    revision_of_job_id: str | None = Field(default=None)
    feedback_round: int = Field(default=0)
    notify_telegram: bool = Field(default=False)
    telegram_chat_id: str | None = Field(default=None)


class JobPayload(JobRequest):
    job_id: str
    created_at: str


class JobAccepted(BaseModel):
    job_id: str
    status: str
    queued_at: datetime


class SynthesisRequest(BaseModel):
    text: str
    language: str = "vi"
    speaker_wav: str
    output_name: str